### ISSUE TITLE
Is it possible to generate a fire effect with this library?

### ISSUE THREAD

**Issue by forseeking** [tizian/particles#1]
This project is great! I managed to build a fire-alike effect with the blob texture, but it is a little bit blur. Can I generate more high quality fire with this library?

**Comment by tizian** [comment]
hi @forseeking 

Thanks! Mostly likely yes---but I'm not an expert on how to actually author nice-looking effects (and of course it depends a lot on the art style you're after...).
The blob is indeed quite blurry IIRC, so your best bet is probably to play with different textures.

**Comment by Ironbell** [comment]
Hi @forseeking 

We made a game using that library and made quite a few fire effects with it. It's all open source, so if you want something like this
![image](https://user-images.githubusercontent.com/9303244/151159599-fb0108f1-8596-4440-9748-8ee7b8a5003a.png)

Feel free to checkout tizian's Cendric2 repository.

**Comment by tizian** [comment]
Right, good point. In particular this directory might be useful:
https://github.com/tizian/Cendric2/tree/master/res/texture/particles

**Comment by forseeking** [comment]
> https://github.com/tizian/Cendric2/tree/master/res/texture/particles

Thanks. I will try different textures. This library is a treasure and it should deserve more stars. 

> Right, good point. In particular this directory might be useful: https://github.com/tizian/Cendric2/tree/master/res/texture/particles
